<div class="post-text" itemprop="text">
<p>I have a Django ORM query like this:</p>
<pre><code>try:
    specialization_object = Specialization.objects.get(name="My Test Specialization")
except Exception as ex:
    print(ex)
</code></pre>
<p>When there occurs an exception then it prints "Specialization matching query does not exist.", but it does not print the line number. How can I trace the line number on which the exception or error occurred?</p>
</div>
<div class="post-text" itemprop="text">
<p>try this:</p>
<pre><code>import logging
logger = logging.getLogger(__name__)

try:
    specialization_object = Specialization.objects.get(name="My Test Specialization")
except Exception as ex:
    logger.info(ex, exc_info=True) # exc_info will add traceback
</code></pre>
<p>further reading see <a href="https://stackoverflow.com/questions/5191830/how-do-i-log-a-python-error-with-debug-information">here</a></p>
</div>
<div class="post-text" itemprop="text">
<p>If you can't for any reason use logging, There's the standard package <a href="https://docs.python.org/2/library/traceback.html" rel="nofollow noreferrer">traceback</a>, and you can do something like:</p>
<pre><code>traceback.print_exc(file=sys.stdout)
</code></pre>
</div>
<div class="post-text" itemprop="text">
<p>I have figured out a simple solution just now:</p>
<pre><code>import traceback
try:
    specialization_object = Specialization.objects.get(name="My Test Specialization")
except Exception as ex:
    print(traceback.format_exc())
</code></pre>
</div>
<span class="comment-copy">use <code>sys.exc_info()</code> <a href="https://docs.python.org/3/library/sys.html#sys.exc_info" rel="nofollow noreferrer">docs.python.org/3/library/sys.html#sys.exc_info</a></span>
<span class="comment-copy">But in this case the subsequent lines won't be executed. I want to handle the exception and also get the exception line number.</span>
<span class="comment-copy">mea culpa - just switched to logging :/</span>
<span class="comment-copy">print(ex, exc_info=True) shows that exc_info is is unexpected argument here.</span>
<span class="comment-copy">my mistake - have updated my code accordingly.</span>
<span class="comment-copy">Or just <code>logger.exception(message)</code>.</span>
