Natural Text
I had this code:Which, when executed, gives this error:So, then, I added foo = 0 at the beginning of the code, and got this output:Now, obviously, it should also be outputting Success, but it isn't.What's the issue?Using Python 3.
The correct way is to pass a dict to exec in python 3 and lookup by key, in python2 your code would work as is because exec is a statement as opposed to a function in python3:Output:execNote The default locals act as described for function locals() below: modifications to the default locals dictionary should not be attempted. Pass an explicit locals dictionary if you need to see effects of the code on locals after function exec() returns.You also need to catch the case where your if  variable > 1 is False as you will never exec the code so foo will never be added.
Reading @Padraic Cunningham's post gave me an idea, which worked as a solution:It's simple: instead of just doing : foo = 1, do : global foo; foo = 1.Changed code:The issue is that exec() is a function rather than a statement in Python 3, so foo was being used as a local variable. (Source: @Padraic Cunningham)


Answer URL
https://docs.python.org/3/library/functions.html#exec
