<div class="post-text" itemprop="text">
<p>I created a class inheriting from <a href="https://docs.python.org/3/library/datetime.html#datetime.datetime" rel="nofollow noreferrer"><code>datetime.datetime</code></a>.</p>
<p>While creating a new instance using the classmethod <a href="https://docs.python.org/3/library/datetime.html#datetime.datetime.fromtimestamp" rel="nofollow noreferrer"><code>fromtimestamp</code></a> it seems to work, <strong>except</strong> if I provide a <code>timezone</code> object. In such case, the returned object is of base type <code>datetime</code>.</p>
<pre><code>import time
from datetime import datetime, timezone

class MyDatetime(datetime):
    pass

MyDatetime.fromtimestamp(time.time())
# MyDatetime(2018, 11, 30, 18, 8, 36, 418105)
# &lt;class '__main__.MyDatetime'&gt;

MyDatetime.fromtimestamp(time.time(), tz=timezone.utc)
# datetime.datetime(2018, 11, 30, 17, 8, 50, 667385, tzinfo=datetime.timezone.utc)
# &lt;class 'datetime.datetime'&gt;
</code></pre>
<p>This seems surprising. I don't see any mention of such weird behavior in the documentation, am I missing something or is it a Python bug?</p>
</div>
<div class="post-text" itemprop="text">
<p><strong><a href="https://bugs.python.org/issue35364" rel="nofollow noreferrer">Cross Posting from Python Bug Tracker</a></strong></p>
<p>It's a side effect of a date arithmetic operation performed while setting timezone.</p>
<ul>
<li>while passing tz info to datetime it invokes <a href="https://github.com/python/cpython/blob/3df85404d4bf420db3362eeae1345f2cad948a71/Lib/datetime.py#L1593" rel="nofollow noreferrer">tz.fromutc()</a></li>
<li>followed by a datetime arithmetic <a href="https://github.com/python/cpython/blob/3df85404d4bf420db3362eeae1345f2cad948a71/Lib/datetime.py#L2188" rel="nofollow noreferrer">here</a></li>
<li>which eventually leads to building a new datetime object <a href="https://github.com/python/cpython/blob/3df85404d4bf420db3362eeae1345f2cad948a71/Lib/datetime.py#L1997-L2000" rel="nofollow noreferrer">here</a></li>
</ul>
<p>I'm not sure if its an expected behaviour</p>
</div>
<span class="comment-copy">Just to concur, I'm also seeing this on my CPython3.7.1 build.</span>
<span class="comment-copy">@TheIncorrigible1 Thanks, I was wondering if that could have been fixed with Python 3.7 (I use 3.6) as I saw mentions of "fromtimestamp" in the issue trackers. I will definitely open a new one, then.</span>
<span class="comment-copy">Opened issue: <a href="https://bugs.python.org/issue35364" rel="nofollow noreferrer">#35364</a></span>
<span class="comment-copy">Thanks for your investigation! :)</span>
